### ISSUE TITLE
smpl_template_mixamo.mtl?

### ISSUE THREAD

**Issue by Liu-xiaoyu11** [wrk226/GarmentAnimationNeRF#1]
Hello, @wrk226:
Your excellent work has been very inspiring to me. However, I encountered an issue while trying to reproduce the code, and I would appreciate any advice you can offer. Specifically, when I run the following command:
python train_net.py --cfg_file configs/zju_mocap_exp/samba-multilayer_16v-2d-3d-v2-2.yaml --train_epochs 400 exp_name samba-multilayer_16v-2d-3d-v2-2 resume True;
I receive a message indicating that it cannot find smpl_template_mixamo.mtl. This file is also missing from the data package I downloaded.
![image](https://github.com/user-attachments/assets/41544817-cbbf-448d-988c-662d27614765)
I look forward to receiving your response as soon as possible, and thank you very much for your assistance.

**Comment by wrk226** [comment]
Sorry for the late reply.

1. The MTL file is not necessary. It won't cause any errors, so you can ignore this warning.  
2. The main issue lies with the PIL package. I believe it might be related to the version of Pillow or Imageio. You can refer to the versions I specified in the `environment.yaml` file and make adjustments accordingly.
